# Generated by Django 5.1.5 on 2025-01-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_parsing', '0004_auto_20220319_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analoglink',
            options={'verbose_name': 'Похожий товар', 'verbose_name_plural': 'Похожие товары'},
        ),
        migrations.AlterModelOptions(
            name='analoglinkprice',
            options={'verbose_name': 'Похожие ссылки', 'verbose_name_plural': 'Похожие ссылки'},
        ),
        migrations.AlterModelOptions(
            name='grouplink',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылка на товар', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.AlterModelOptions(
            name='pricelink',
            options={'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='Название товара(артикул и т.п.)'),
        ),
    ]
